//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace кафе
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<Employeess> Employeess { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Request_Dishes> Request_Dishes { get; set; }
        public virtual DbSet<Request_Drink> Request_Drink { get; set; }
        public virtual DbSet<Request_Employee> Request_Employee { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Userss> Userss { get; set; }
        public virtual DbSet<WorkShifts> WorkShifts { get; set; }
        public virtual DbSet<WorkShifts_Employee> WorkShifts_Employee { get; set; }
    }
}
