//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace кафе
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Employee
    {
        public int RK_Request_Employee { get; set; }
        public Nullable<int> FK_Request { get; set; }
        public Nullable<int> FK_Employee { get; set; }
    
        public virtual Employeess Employeess { get; set; }
        public virtual Request Request { get; set; }
    }
}
