//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace кафе
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShifts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkShifts()
        {
            this.WorkShifts_Employee = new HashSet<WorkShifts_Employee>();
        }
    
        public int RK_WorkShifts { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkShifts_Employee> WorkShifts_Employee { get; set; }
    }
}
